# Generated by Django 4.1.5 on 2023-05-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
